# Generated by Django 2.0.3 on 2018-04-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default=False, max_length=10000)),
                ('rating', models.FloatField(default=5.0)),
                ('isbn', models.ForeignKey(default='Not available', on_delete=django.db.models.deletion.CASCADE, to='pages.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='pages.OurUser')),
            ],
        ),
    ]
