# Generated by Django 2.0.3 on 2018-04-24 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20180423_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
