# Generated by Django 2.0.3 on 2018-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_review_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate_date',
            field=models.DateField(auto_now=True),
        ),
    ]
