# Generated by Django 2.0.3 on 2018-03-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('wiki_link', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Boiii',
            fields=[
                ('book_id', models.CharField(default='Not available', max_length=50, primary_key=True, serialize=False)),
                ('condition', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(default='Not available', max_length=50, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(default='Not available', max_length=100)),
                ('publish_date', models.DateField(default='17-02-1996')),
                ('publisher', models.CharField(default='Not available', max_length=100)),
                ('amazon_link', models.CharField(default='Not available', max_length=500)),
                ('edition', models.IntegerField(default=1)),
                ('pages', models.IntegerField(default=1)),
                ('count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('book_name', models.CharField(default='Not available', max_length=100)),
                ('author_id', models.ForeignKey(default='Not available', on_delete=django.db.models.deletion.CASCADE, to='pages.Author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='Not available', max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='Not available', max_length=100)),
                ('batch', models.IntegerField(default=21)),
                ('roll_no', models.IntegerField(default=26)),
                ('mail_id', models.CharField(default='Not available', max_length=100)),
                ('donate_count', models.IntegerField(default=0)),
                ('phone', models.CharField(default='Not available', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boiii',
            name='isbn',
            field=models.ForeignKey(default='Not available', on_delete=django.db.models.deletion.CASCADE, to='pages.User'),
        ),
        migrations.AddField(
            model_name='boiii',
            name='user_id',
            field=models.ForeignKey(default='Not available', on_delete=django.db.models.deletion.CASCADE, to='pages.Book'),
        ),
    ]
