# Generated by Django 2.0.3 on 2018-04-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='boiii',
            name='receiver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='pages.OurUser'),
        ),
        migrations.AlterField(
            model_name='boiii',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='pages.OurUser'),
        ),
    ]
