# Generated by Django 2.0.3 on 2018-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
