# Generated by Django 2.0.3 on 2018-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180416_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
