# Generated by Django 2.0.3 on 2018-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180421_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_link',
            field=models.CharField(default='Not available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Not available', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='topic_name',
            field=models.CharField(default='Not available', max_length=500),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='mail_id',
            field=models.CharField(default='Not available', max_length=500),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='user_name',
            field=models.CharField(default='Not available', max_length=500),
        ),
    ]
