# Generated by Django 2.0.3 on 2018-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book_name',
            field=models.CharField(default='Not available', max_length=500),
        ),
    ]
