# Generated by Django 2.0.3 on 2018-04-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=256)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='pages.OurUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='pages.OurUser')),
            ],
        ),
    ]
