# Generated by Django 2.0.3 on 2018-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
